export const extractionJsonSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "document_type",
    "certificate_standard",
    "certificate_number",
    "organization_name",
    "organization_address",
    "scope_of_certification",
    "certification_body",
    "accreditation_body",
    "issue_date",
    "expiry_date",
    "original_certification_date",
    "surveillance_dates",
    "iaf_codes",
    "ea_codes",
    "authorized_signatory",
    "site_addresses",
    "registration_numbers",
    "qr_code_detected",
    "seal_detected",
    "logo_detected",
    "certificate_status",
    "confidence_score",
    "possible_issues",
    "raw_summary"
  ],
  properties: {
    document_type: { anyOf: [{ type: "string" }, { type: "null" }] },
    certificate_standard: { anyOf: [{ type: "string" }, { type: "null" }] },
    certificate_number: { anyOf: [{ type: "string" }, { type: "null" }] },
    organization_name: { anyOf: [{ type: "string" }, { type: "null" }] },
    organization_address: { anyOf: [{ type: "string" }, { type: "null" }] },
    scope_of_certification: { anyOf: [{ type: "string" }, { type: "null" }] },
    certification_body: { anyOf: [{ type: "string" }, { type: "null" }] },
    accreditation_body: { anyOf: [{ type: "string" }, { type: "null" }] },
    issue_date: { anyOf: [{ type: "string" }, { type: "null" }] },
    expiry_date: { anyOf: [{ type: "string" }, { type: "null" }] },
    original_certification_date: { anyOf: [{ type: "string" }, { type: "null" }] },
    surveillance_dates: { type: "array", items: { type: "string" } },
    iaf_codes: { type: "array", items: { type: "string" } },
    ea_codes: { type: "array", items: { type: "string" } },
    authorized_signatory: { anyOf: [{ type: "string" }, { type: "null" }] },
    site_addresses: { type: "array", items: { type: "string" } },
    registration_numbers: { type: "array", items: { type: "string" } },
    qr_code_detected: { type: "boolean" },
    seal_detected: { type: "boolean" },
    logo_detected: { type: "boolean" },
    certificate_status: {
      type: "string",
      enum: ["valid", "expired", "suspicious", "incomplete", "pending_review", "unknown"]
    },
    confidence_score: { type: "number", minimum: 0, maximum: 1 },
    possible_issues: { type: "array", items: { type: "string" } },
    raw_summary: { anyOf: [{ type: "string" }, { type: "null" }] }
  }
} as const;
